#开发环境配置
server:
  #端口
  port: 8081
  #Session过期时间
  session:
    timeout: 3600

#spring
spring:
  datasource:
    name: cop
    #    useAffectedRows，sql执行后返回受影响的行数
    url: jdbc:mysql://127.0.0.1:3306/${spring.datasource.name}?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useAffectedRows=true&useSSL=false
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  # thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    sufifix: .html
    cache: false
    mode: LEGACYHTML5
    static-locations: classpath:/static/
    content-type: text/html

  #静态资源访问
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/,classpath:/public/

  devtools:
    restart:
       additional=../dataprovider
       exclude=../shiro


# mybatis-plus
mybatis-plus:
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3

#日志显示级别
logging:
  level:
    com:
      xxlllq:
        dataprovider: DEBUG
        web: DEBUG
        shiro: DEBUG



